POST http://127.0.0.1:8000/login/
Content-Type: application/json 

{"username": "taw55", "password": "1"}

### 


POST http://127.0.0.1:8000/signup
Content-Type: application/json 

{ "username":"taw57", "password": "1", "email": "123@gmail.com" }

###



GET http://127.0.0.1:8000/test_token/
Content-Type: application/json 
Authorization: Token eef70b7463b152d922d44af7b79116749aeab62d

{}
###

POST http://127.0.0.1:8000/toggle_card/firstChapter/1/
Content-Type: application/json 
Authorization: Token 2725a5d1c18bb6e78f35cd3bf1346a7cb442633b
###

GET http://127.0.0.1:8000/take_cards/
Content-Type: application/json 
Authorization: Token 2725a5d1c18bb6e78f35cd3bf1346a7cb442633b
###


GET http://127.0.0.1:8000/change_warn/
Content-Type: application/json 
Authorization: Token b45168fd3cc38233aee732bfac516db758201023
###

GET http://127.0.0.1:8000/take_user_data/
Content-Type: application/json 
Authorization: Token bca3dcfb6e7258c5377e8868fa8c87b0f57b0905
###


GET http://127.0.0.1:8000/take_text/
Content-Type: application/json 

###



### 
POST http://127.0.0.1:8000/create_text/
Content-Type: application/json 

{ "title": "O deuss", "content": "O jessus", "version": "nvssi" }

###

POST http://127.0.0.1:8000/conclude_devotional/1/
Content-Type: application/json 
Authorization: Token 06a7ad89d395e5be58a7de12c76475ca11de512e
###
