# Generated by Django 5.0.2 on 2024-03-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleTexts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsdevotional',
            name='published_date',
        ),
    ]
