# Generated by Django 5.0.2 on 2024-03-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleTexts', '0003_remove_textsdevotional_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsdevotional',
            name='concluded',
        ),
    ]
