# Generated by Django 5.0.2 on 2024-03-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleTexts', '0003_textsdevotional_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsdevotional',
            name='chapter',
            field=models.CharField(default='..', max_length=30),
            preserve_default=False,
        ),
    ]
