# Generated by Django 5.0.2 on 2024-03-06 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleTexts', '0004_remove_textsdevotional_concluded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsdevotional',
            name='concluded_by',
        ),
        migrations.AddField(
            model_name='textsdevotional',
            name='concluded_by',
            field=models.ManyToManyField(related_name='concluded_devotionals', to=settings.AUTH_USER_MODEL),
        ),
    ]
