# Generated by Django 5.0.2 on 2024-03-08 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allChapters', models.JSONField(blank=True, default={'firstChapter': [{'completed': False, 'id': 1}, {'completed': False, 'id': 2}, {'completed': False, 'id': 3}, {'completed': False, 'id': 4}]}, null=True)),
                ('devotionalWarn', models.BooleanField(default=False)),
                ('myBirds', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
