# Generated by Django 5.0.2 on 2024-03-01 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstCard', models.JSONField(blank=True, default=[{'completed': False, 'id': 1, 'title': 'be a friend of jesus'}, {'completed': False, 'id': 2, 'title': 'knowing the word of god'}, {'completed': False, 'id': 3, 'title': 'jesus and his sheep'}], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
