# Generated by Django 5.0.2 on 2024-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstCard',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstChapter',
            field=models.JSONField(blank=True, default=[{'completed': False, 'id': 1}, {'completed': False, 'id': 2}, {'completed': False, 'id': 3}], null=True),
        ),
    ]
