# Generated by Django 5.0.2 on 2024-03-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='myBirds',
        ),
    ]
