# Generated by Django 5.0.2 on 2024-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleAuth', '0002_remove_profile_mybirds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myBirds',
            field=models.IntegerField(default=0),
        ),
    ]
