# Generated by Django 5.0.2 on 2024-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleAuth', '0002_remove_profile_firstcard_profile_firstchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstChapter',
            field=models.JSONField(blank=True, default={'firstChapter': [{'completed': False, 'id': 1}, {'completed': False, 'id': 2}, {'completed': False, 'id': 3}, {'completed': False, 'id': 4}]}, null=True),
        ),
    ]
