# Generated by Django 5.0.2 on 2024-03-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleAuth', '0003_alter_profile_firstchapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstChapter',
            new_name='allChapters',
        ),
    ]
