# Generated by Django 5.0.2 on 2024-03-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleAuth', '0003_profile_mybirds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='myBirds',
            new_name='myBibles',
        ),
        migrations.AddField(
            model_name='profile',
            name='myPrays',
            field=models.IntegerField(default=0),
        ),
    ]
