# Generated by Django 5.0.2 on 2024-03-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleAuth', '0004_rename_firstchapter_profile_allchapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allChapters',
            field=models.JSONField(blank=True, default={'capitulo1': [{'completed': False, 'id': 1}, {'completed': False, 'id': 2}, {'completed': False, 'id': 3}, {'completed': False, 'id': 4}]}, null=True),
        ),
    ]
